name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 10.18.1

jobs:
  build_and_publish:
    name: Build and publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      - name: Build and check size
        uses: andresz1/size-limit-action@v1.4.0
        if: github.ref != 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install

      - name: Build and check size (manually)
        if: github.ref == 'refs/heads/master'
        run: yarn size

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment-environment: Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  checks:
    name: Checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      - name: Linter
        run: yarn lint

      - name: Unit tests
        run: yarn unit
