name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 12.18.3

jobs:
  build_and_publish:
    name: Build and publish

    runs-on: ubuntu-latest

    outputs:
      deploy-url: ${{ steps.deploy.outputs.deploy-url }}

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Check size
        run: yarn size

      - name: Deploy to Netlify
        id: deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment-environment: Netlify
          deploy-message: ${{ github.event.pull_request.title }}
          enable-commit-comment: false
          enable-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      - name: Linter
        run: yarn lint

  unit:
    name: Unit-tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      - name: Run unit-tests
        run: yarn unit

  e2e:
    name: E2E-tests

    runs-on: ubuntu-latest

    needs: build_and_publish

    container: instantpreview/cypress

    steps:
      - uses: actions/checkout@v2

      - name: Run e2e-tests
        uses: cypress-io/github-action@v2
        with:
          browser: electron
          headless: true
          env: url=${{needs.build_and_publish.outputs.deploy-url}}

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-diff
          path: cypress/snapshots/*/__diff_output__/
